/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.gui;
import javax.swing.JTextField; //Permite usar los campos de Texto
/**
 *
 * @author Alejandrito
 */
public class Eventos extends javax.swing.JFrame {

    //Elimina o vuelve a ingresar el texto predeterminado de los campos de textos, en caso de que esten vacios
    public void validarcampoModerador(JTextField campo, String textopredeterminado, JTextField... otrosCampos){ 
        if (campo.getText().equals(textopredeterminado)) {
            herramientasVentanas.campovacio(campo, "", true);
        }
        for (JTextField otroCampo : otrosCampos) {
            if (otroCampo.getText().isEmpty()) {
                String mensaje = "";
                if (otroCampo == campometodo) {
                    mensaje = "Practico, Teorico, etc...";
                } else if (otroCampo == campoexpint) {
                    mensaje = "X Años de Experiencia";
                } else if (otroCampo == camponombre) {
                    mensaje = "Nombre de la Persona";
                } else if (otroCampo == campocedula) {
                    mensaje = "V-XX.XXX.XX";
                } else if (otroCampo == campocorreo) {
                    mensaje = "Correo personal";
                } else if (otroCampo == campotlf) {
                    mensaje = "Nro. Personal";
                } else if (otroCampo == campoexp){
                    mensaje = "Descripcion (No es obligatorio)";
                }
                herramientasVentanas.campovacio(otroCampo, mensaje, false);
            }
        }
    }
    
     public void validarcampoEvento(JTextField campo, String textopredeterminado, JTextField... otrosCampos){ 
        if (campo.getText().equals(textopredeterminado)) {
            herramientasVentanas.campovacio(campo, "", true);
        }
        
        for (JTextField otroCampo : otrosCampos) {
            if (otroCampo.getText().isEmpty()) {
                String mensaje = "";
                if (otroCampo == campoevnombre) {
                    mensaje = "Ingrese el nombre del evento";
                } else if (otroCampo == campolugar) {
                    mensaje = "Direccion";
                } else if (otroCampo == campocapMax) {
                    mensaje = "Participantes que asistiran";
                } 
                herramientasVentanas.campovacio(otroCampo, mensaje, false);
            }
        }
    }
    
    private MainWindow principal; //Me permitra volver a la ventana principal (Referencia)
    
    
    public Eventos() {
        initComponents();
    }
    
     public Eventos(MainWindow principal) {
        initComponents();
        this.principal = principal;
        camponombre.setName("camponombre");
        campocedula.setName("campocedula");
        campotlf.setName("campotlf");
        campocorreo.setName("campocorreo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horaComenzar = new com.raven.swing.TimePicker();
        horaFinal = new com.raven.swing.TimePicker();
        jMenuItem1 = new javax.swing.JMenuItem();
        padre = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        containerprincipal = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        ventana = new javax.swing.JComboBox<>();
        containerCartas = new javax.swing.JPanel();
        containerEventos = new javax.swing.JPanel();
        footereventos = new javax.swing.JPanel();
        salireventos = new javax.swing.JButton();
        limpiarEventos = new javax.swing.JButton();
        registrarEventos = new javax.swing.JButton();
        titulo1 = new javax.swing.JPanel();
        titulomoderador1 = new javax.swing.JLabel();
        metodomoderar1 = new javax.swing.JLabel();
        metodomoderar3 = new javax.swing.JLabel();
        metodomoderar4 = new javax.swing.JLabel();
        metodomoderar5 = new javax.swing.JLabel();
        metodomoderar6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        metodomoderar2 = new javax.swing.JLabel();
        metodomoderar7 = new javax.swing.JLabel();
        campoevnombre = new javax.swing.JTextField();
        campolugar = new javax.swing.JTextField();
        campodescripcion = new javax.swing.JTextField();
        campocapMax = new javax.swing.JTextField();
        botonComienzo = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        calendario = new de.wannawork.jcalendar.JCalendarComboBox();
        metodomoderar8 = new javax.swing.JLabel();
        containerMod = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        salirMod = new javax.swing.JButton();
        limpiarMod = new javax.swing.JButton();
        registrarMod = new javax.swing.JButton();
        superior = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        titulomoderador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campocorreo = new javax.swing.JTextField();
        camponombre = new javax.swing.JTextField();
        campocedula = new javax.swing.JTextField();
        campotlf = new javax.swing.JTextField();
        separadornombre = new javax.swing.JSeparator();
        separadorcorreo = new javax.swing.JSeparator();
        separadorcedula = new javax.swing.JSeparator();
        separadortlf = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        campometodo = new javax.swing.JTextField();
        metodomoderar = new javax.swing.JLabel();
        experiencias = new javax.swing.JLabel();
        experienciascantidad = new javax.swing.JLabel();
        campoexpint = new javax.swing.JTextField();
        campoexp = new javax.swing.JTextField();

        horaComenzar.setForeground(new java.awt.Color(255, 102, 102));

        horaFinal.setForeground(new java.awt.Color(255, 153, 153));

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        padre.setBackground(new java.awt.Color(255, 228, 228));
        padre.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/eventos/corporate.png"))); // NOI18N
        jLabel15.setText("Organizacion del Evento  ");
        jLabel15.setFocusable(false);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        header.add(jLabel15);

        padre.add(header, java.awt.BorderLayout.PAGE_START);

        containerprincipal.setBackground(new java.awt.Color(255, 228, 228));
        containerprincipal.setLayout(new java.awt.BorderLayout());

        menu.setBackground(new java.awt.Color(252, 186, 186));
        menu.setPreferredSize(new java.awt.Dimension(737, 70));

        ventana.setBackground(new java.awt.Color(255, 204, 204));
        ventana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ventana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderador", "Eventos" }));
        ventana.setSelectedIndex(1);
        ventana.setMinimumSize(new java.awt.Dimension(138, 27));
        ventana.setPreferredSize(new java.awt.Dimension(138, 27));
        ventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        containerprincipal.add(menu, java.awt.BorderLayout.PAGE_START);

        containerCartas.setBackground(new java.awt.Color(255, 228, 228));
        containerCartas.setLayout(new java.awt.CardLayout());

        containerEventos.setBackground(new java.awt.Color(255, 228, 228));

        footereventos.setBackground(new java.awt.Color(255, 204, 204));

        salireventos.setBackground(new java.awt.Color(252, 186, 186));
        salireventos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        salireventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/exit.png"))); // NOI18N
        salireventos.setText("Salir");
        salireventos.setBorder(null);
        salireventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salireventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salireventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salireventosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salireventosMousePressed(evt);
            }
        });
        salireventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salireventosActionPerformed(evt);
            }
        });

        limpiarEventos.setBackground(new java.awt.Color(252, 186, 186));
        limpiarEventos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        limpiarEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/data-cleaning.png"))); // NOI18N
        limpiarEventos.setText("Limpiar");
        limpiarEventos.setBorder(null);
        limpiarEventos.setBorderPainted(false);
        limpiarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarEventosMouseExited(evt);
            }
        });
        limpiarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarEventosActionPerformed(evt);
            }
        });

        registrarEventos.setBackground(new java.awt.Color(252, 186, 186));
        registrarEventos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        registrarEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/verify.png"))); // NOI18N
        registrarEventos.setText("Registrar");
        registrarEventos.setBorder(null);
        registrarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarEventosMouseExited(evt);
            }
        });
        registrarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footereventosLayout = new javax.swing.GroupLayout(footereventos);
        footereventos.setLayout(footereventosLayout);
        footereventosLayout.setHorizontalGroup(
            footereventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footereventosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(salireventos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(limpiarEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(registrarEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        footereventosLayout.setVerticalGroup(
            footereventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footereventosLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(footereventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salireventos)
                    .addComponent(limpiarEventos)
                    .addComponent(registrarEventos))
                .addGap(42, 42, 42))
        );

        titulo1.setBackground(new java.awt.Color(255, 204, 204));

        titulomoderador1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        titulomoderador1.setForeground(new java.awt.Color(255, 255, 255));
        titulomoderador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulomoderador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/eventos/calendar.png"))); // NOI18N
        titulomoderador1.setText("Registro del Evento ");
        titulomoderador1.setToolTipText("");
        titulomoderador1.setFocusable(false);
        titulomoderador1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout titulo1Layout = new javax.swing.GroupLayout(titulo1);
        titulo1.setLayout(titulo1Layout);
        titulo1Layout.setHorizontalGroup(
            titulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titulo1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulomoderador1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        titulo1Layout.setVerticalGroup(
            titulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(titulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titulo1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulomoderador1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        metodomoderar1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar1.setText(" Tipo de Evento ");

        metodomoderar3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar3.setText("Lugar del Evento");

        metodomoderar4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar4.setText("Capacidad de Participantes");

        metodomoderar5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar5.setText("Hora a Comenzar");

        metodomoderar6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar6.setText("Hora a Finalizar");

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conferencia", "Jornada", "Seminario", "Taller" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        metodomoderar2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar2.setText("Nombre del Evento");

        metodomoderar7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar7.setText("Descripcion");

        campoevnombre.setBackground(new java.awt.Color(255, 204, 204));
        campoevnombre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campoevnombre.setForeground(java.awt.Color.gray);
        campoevnombre.setText("Ingrese el nombre del evento");
        campoevnombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campoevnombre.setMinimumSize(new java.awt.Dimension(200, 21));
        campoevnombre.setPreferredSize(new java.awt.Dimension(200, 21));
        campoevnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoevnombreMousePressed(evt);
            }
        });
        campoevnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoevnombreActionPerformed(evt);
            }
        });

        campolugar.setBackground(new java.awt.Color(255, 204, 204));
        campolugar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campolugar.setForeground(java.awt.Color.gray);
        campolugar.setText("Direccion");
        campolugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campolugar.setMinimumSize(new java.awt.Dimension(200, 21));
        campolugar.setPreferredSize(new java.awt.Dimension(200, 21));
        campolugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campolugarMousePressed(evt);
            }
        });

        campodescripcion.setBackground(new java.awt.Color(255, 204, 204));
        campodescripcion.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campodescripcion.setForeground(java.awt.Color.gray);
        campodescripcion.setText("Descripcion (No es obligatorio)");
        campodescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campodescripcion.setMinimumSize(new java.awt.Dimension(200, 21));
        campodescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campodescripcionMousePressed(evt);
            }
        });

        campocapMax.setBackground(new java.awt.Color(255, 204, 204));
        campocapMax.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campocapMax.setForeground(java.awt.Color.gray);
        campocapMax.setText("Participantes que asistiran");
        campocapMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campocapMax.setMinimumSize(new java.awt.Dimension(200, 21));
        campocapMax.setPreferredSize(new java.awt.Dimension(200, 21));
        campocapMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campocapMaxMousePressed(evt);
            }
        });
        campocapMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocapMaxActionPerformed(evt);
            }
        });

        botonComienzo.setBackground(new java.awt.Color(252, 186, 186));
        botonComienzo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonComienzo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/eventos/clock.png"))); // NOI18N
        botonComienzo.setText("Selecciona la Hora");
        botonComienzo.setBorder(null);
        botonComienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonComienzoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonComienzoMouseExited(evt);
            }
        });
        botonComienzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComienzoActionPerformed(evt);
            }
        });

        botonFinalizar.setBackground(new java.awt.Color(252, 186, 186));
        botonFinalizar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/eventos/technology.png"))); // NOI18N
        botonFinalizar.setText("Selecciona la Hora");
        botonFinalizar.setBorder(null);
        botonFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonFinalizarMouseExited(evt);
            }
        });
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        calendario.setBackground(new java.awt.Color(255, 153, 153));
        calendario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calendario.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        calendario.setMinimumSize(new java.awt.Dimension(125, 30));

        metodomoderar8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar8.setText("Fecha del Evento");

        javax.swing.GroupLayout containerEventosLayout = new javax.swing.GroupLayout(containerEventos);
        containerEventos.setLayout(containerEventosLayout);
        containerEventosLayout.setHorizontalGroup(
            containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footereventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerEventosLayout.createSequentialGroup()
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerEventosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campolugar, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(campoevnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(containerEventosLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(metodomoderar3))
                    .addGroup(containerEventosLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(metodomoderar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerEventosLayout.createSequentialGroup()
                            .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerEventosLayout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(campocapMax, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerEventosLayout.createSequentialGroup()
                            .addComponent(metodomoderar4)
                            .addGap(50, 50, 50)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerEventosLayout.createSequentialGroup()
                        .addComponent(metodomoderar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(metodomoderar8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(containerEventosLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(metodomoderar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(metodomoderar6)
                .addGap(106, 106, 106))
            .addGroup(containerEventosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(botonComienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerEventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campodescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(containerEventosLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(metodomoderar7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerEventosLayout.setVerticalGroup(
            containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerEventosLayout.createSequentialGroup()
                .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodomoderar1)
                    .addComponent(metodomoderar2)
                    .addComponent(metodomoderar8))
                .addGap(18, 18, 18)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoevnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodomoderar3)
                    .addComponent(metodomoderar4))
                .addGap(18, 18, 18)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campolugar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campocapMax, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodomoderar5)
                    .addComponent(metodomoderar6))
                .addGap(18, 18, 18)
                .addGroup(containerEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComienzo)
                    .addComponent(botonFinalizar))
                .addGap(50, 50, 50)
                .addComponent(metodomoderar7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campodescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(footereventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerCartas.add(containerEventos, "card3");

        containerMod.setBackground(new java.awt.Color(255, 228, 228));

        footer.setBackground(new java.awt.Color(255, 204, 204));

        salirMod.setBackground(new java.awt.Color(252, 186, 186));
        salirMod.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        salirMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/exit.png"))); // NOI18N
        salirMod.setText("Salir");
        salirMod.setBorder(null);
        salirMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirModMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirModMousePressed(evt);
            }
        });
        salirMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirModActionPerformed(evt);
            }
        });

        limpiarMod.setBackground(new java.awt.Color(252, 186, 186));
        limpiarMod.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        limpiarMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/data-cleaning.png"))); // NOI18N
        limpiarMod.setText("Limpiar");
        limpiarMod.setBorder(null);
        limpiarMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarModMouseExited(evt);
            }
        });
        limpiarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarModActionPerformed(evt);
            }
        });

        registrarMod.setBackground(new java.awt.Color(252, 186, 186));
        registrarMod.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        registrarMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/Participante/verify.png"))); // NOI18N
        registrarMod.setText("Registrar");
        registrarMod.setBorder(null);
        registrarMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarModMouseExited(evt);
            }
        });
        registrarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(salirMod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(limpiarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(registrarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirMod)
                    .addComponent(limpiarMod)
                    .addComponent(registrarMod))
                .addGap(42, 42, 42))
        );

        superior.setBackground(new java.awt.Color(255, 228, 228));

        titulo.setBackground(new java.awt.Color(255, 204, 204));

        titulomoderador.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        titulomoderador.setForeground(new java.awt.Color(255, 255, 255));
        titulomoderador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulomoderador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/Imagenes/eventos/crown.png"))); // NOI18N
        titulomoderador.setText("Registro del Moderador  ");
        titulomoderador.setFocusable(false);
        titulomoderador.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulomoderador)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulomoderador)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Cedula");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Correo");

        campocorreo.setBackground(new java.awt.Color(255, 228, 228));
        campocorreo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campocorreo.setForeground(java.awt.Color.gray);
        campocorreo.setText("Correo personal");
        campocorreo.setToolTipText("");
        campocorreo.setActionCommand("<Not Set>");
        campocorreo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        campocorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campocorreo.setPreferredSize(new java.awt.Dimension(200, 17));
        campocorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campocorreoMousePressed(evt);
            }
        });
        campocorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocorreoActionPerformed(evt);
            }
        });

        camponombre.setBackground(new java.awt.Color(255, 228, 228));
        camponombre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        camponombre.setForeground(java.awt.Color.gray);
        camponombre.setText("Nombre de la Persona");
        camponombre.setToolTipText("");
        camponombre.setActionCommand("<Not Set>");
        camponombre.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        camponombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        camponombre.setPreferredSize(new java.awt.Dimension(200, 17));
        camponombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camponombreMousePressed(evt);
            }
        });
        camponombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponombreActionPerformed(evt);
            }
        });

        campocedula.setBackground(new java.awt.Color(255, 228, 228));
        campocedula.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campocedula.setForeground(java.awt.Color.gray);
        campocedula.setText("V-XX.XXX.XX");
        campocedula.setToolTipText("");
        campocedula.setActionCommand("<Not Set>");
        campocedula.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        campocedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campocedula.setPreferredSize(new java.awt.Dimension(200, 17));
        campocedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campocedulaMousePressed(evt);
            }
        });

        campotlf.setBackground(new java.awt.Color(255, 228, 228));
        campotlf.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campotlf.setForeground(java.awt.Color.gray);
        campotlf.setText("Nro. Personal");
        campotlf.setToolTipText("");
        campotlf.setActionCommand("<Not Set>");
        campotlf.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        campotlf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campotlf.setPreferredSize(new java.awt.Dimension(200, 17));
        campotlf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campotlfMousePressed(evt);
            }
        });

        separadornombre.setForeground(new java.awt.Color(0, 0, 0));

        separadorcorreo.setForeground(new java.awt.Color(0, 0, 0));

        separadorcedula.setForeground(new java.awt.Color(0, 0, 0));

        separadortlf.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadornombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(separadorcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadortlf, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campotlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campocedula, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campotlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadornombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadortlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addGroup(superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campocedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separadorcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)))
                .addGap(0, 0, 0)
                .addComponent(separadorcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jSeparator2.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(255, 153, 153));

        campometodo.setBackground(new java.awt.Color(255, 204, 204));
        campometodo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campometodo.setForeground(java.awt.Color.gray);
        campometodo.setText("Practico, Teorico, etc...");
        campometodo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campometodo.setMinimumSize(new java.awt.Dimension(200, 21));
        campometodo.setPreferredSize(new java.awt.Dimension(200, 21));
        campometodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campometodoMousePressed(evt);
            }
        });

        metodomoderar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metodomoderar.setText("Metodo de Moderacion");

        experiencias.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        experiencias.setText("Experiencias Previas");

        experienciascantidad.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        experienciascantidad.setText("Años de Experiencia");

        campoexpint.setBackground(new java.awt.Color(255, 204, 204));
        campoexpint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campoexpint.setForeground(java.awt.Color.gray);
        campoexpint.setText("X Años de Experiencia");
        campoexpint.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campoexpint.setMinimumSize(new java.awt.Dimension(200, 21));
        campoexpint.setPreferredSize(new java.awt.Dimension(200, 21));
        campoexpint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoexpintMousePressed(evt);
            }
        });
        campoexpint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoexpintActionPerformed(evt);
            }
        });

        campoexp.setBackground(new java.awt.Color(255, 204, 204));
        campoexp.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        campoexp.setForeground(java.awt.Color.gray);
        campoexp.setText("Descripcion (No es obligatorio)");
        campoexp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campoexp.setMinimumSize(new java.awt.Dimension(200, 21));
        campoexp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoexpMousePressed(evt);
            }
        });
        campoexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoexpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerModLayout = new javax.swing.GroupLayout(containerMod);
        containerMod.setLayout(containerModLayout);
        containerModLayout.setHorizontalGroup(
            containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(containerModLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metodomoderar)
                    .addComponent(campometodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoexpint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experienciascantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerModLayout.createSequentialGroup()
                        .addComponent(campoexp, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerModLayout.createSequentialGroup()
                        .addComponent(experiencias)
                        .addGap(139, 139, 139))))
        );
        containerModLayout.setVerticalGroup(
            containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerModLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodomoderar)
                    .addComponent(experiencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campometodo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(experienciascantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoexpint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerCartas.add(containerMod, "card2");

        containerprincipal.add(containerCartas, java.awt.BorderLayout.CENTER);

        padre.add(containerprincipal, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirModMouseEntered
        herramientasVentanas.cambiarColor(salirMod, true);
    }//GEN-LAST:event_salirModMouseEntered

    private void salirModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirModMouseExited
        herramientasVentanas.cambiarColor(salirMod, false);
    }//GEN-LAST:event_salirModMouseExited

    private void salirModMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirModMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirModMousePressed

    private void salirModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirModActionPerformed
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_salirModActionPerformed

    private void limpiarModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarModMouseEntered
        herramientasVentanas.cambiarColor(limpiarMod, true);
    }//GEN-LAST:event_limpiarModMouseEntered

    private void limpiarModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarModMouseExited
        herramientasVentanas.cambiarColor(limpiarMod, false);
    }//GEN-LAST:event_limpiarModMouseExited

    private void limpiarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarModActionPerformed
        herramientasVentanas.campovacio(campometodo, "Practico, Teorico, etc...", false);
        herramientasVentanas.campovacio(campoexp, "Descripcion (No es obligatorio)", false);
        herramientasVentanas.campovacio(campoexpint, "X Años de Experiencia", false);
        herramientasVentanas.campovacio(camponombre, "Nombre de la Persona", false);
        herramientasVentanas.campovacio(campocedula, "V-XX.XXX.XX", false);
        herramientasVentanas.campovacio(campotlf, "Nro. Personal", false);
        herramientasVentanas.campovacio(campocorreo, "Correo personal", false);
    }//GEN-LAST:event_limpiarModActionPerformed

    private void registrarModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarModMouseEntered
        herramientasVentanas.cambiarColor(registrarMod, true);
    }//GEN-LAST:event_registrarModMouseEntered

    private void registrarModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarModMouseExited
        herramientasVentanas.cambiarColor(registrarMod, false);
    }//GEN-LAST:event_registrarModMouseExited

    private void registrarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarModActionPerformed
        //Aqui habria logica, si tuviera una
    }//GEN-LAST:event_registrarModActionPerformed

    private void campocorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campocorreoMousePressed
       herramientasVentanas.validarCampoprincipal(campocorreo, "Correo personal", campotlf, camponombre, campocedula);
    }//GEN-LAST:event_campocorreoMousePressed

    private void campocorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocorreoActionPerformed

    private void camponombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camponombreMousePressed
        herramientasVentanas.validarCampoprincipal(camponombre, "Nombre de la Persona", campotlf, campocedula, campocorreo);
    }//GEN-LAST:event_camponombreMousePressed

    private void camponombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponombreActionPerformed

    private void campocedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campocedulaMousePressed
        herramientasVentanas.validarCampoprincipal(campocedula, "V-XX.XXX.XX", campotlf, camponombre, campocorreo); 

    }//GEN-LAST:event_campocedulaMousePressed

    private void campotlfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campotlfMousePressed
        herramientasVentanas.validarCampoprincipal(campotlf, "Nro. Personal", campocedula, camponombre, campocorreo);

    }//GEN-LAST:event_campotlfMousePressed

    private void campometodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campometodoMousePressed
        validarcampoModerador(campometodo,"Practico, Teorico, etc...", campoexpint, camponombre, campotlf, campocorreo, campocedula);
    }//GEN-LAST:event_campometodoMousePressed

    private void campoexpintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoexpintMousePressed
        validarcampoModerador(campoexpint,"X Años de Experiencia", campometodo, camponombre, campotlf, campocorreo, campocedula);
    }//GEN-LAST:event_campoexpintMousePressed

    private void salireventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salireventosMouseEntered
        herramientasVentanas.cambiarColor(salireventos, true);
    }//GEN-LAST:event_salireventosMouseEntered

    private void salireventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salireventosMouseExited
        herramientasVentanas.cambiarColor(salireventos, false);
    }//GEN-LAST:event_salireventosMouseExited

    private void salireventosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salireventosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salireventosMousePressed

    private void salireventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salireventosActionPerformed
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_salireventosActionPerformed

    private void limpiarEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarEventosMouseEntered
        herramientasVentanas.cambiarColor(limpiarEventos, true);
    }//GEN-LAST:event_limpiarEventosMouseEntered

    private void limpiarEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarEventosMouseExited
        herramientasVentanas.cambiarColor(limpiarEventos, false);
    }//GEN-LAST:event_limpiarEventosMouseExited

    private void limpiarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarEventosActionPerformed
        herramientasVentanas.campovacio(campoevnombre, "Ingrese el nombre del evento", false);
        herramientasVentanas.campovacio(campolugar, "Direccion", false);
        
        herramientasVentanas.campovacio(campodescripcion, "Descripcion (No es obligatorio)", false);
        herramientasVentanas.campovacio(campocapMax, "Participantes que asistiran", false);
    }//GEN-LAST:event_limpiarEventosActionPerformed

    private void registrarEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEventosMouseEntered
        herramientasVentanas.cambiarColor(registrarEventos, true);
    }//GEN-LAST:event_registrarEventosMouseEntered

    private void registrarEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEventosMouseExited
       herramientasVentanas.cambiarColor(registrarEventos, false);
    }//GEN-LAST:event_registrarEventosMouseExited

    private void registrarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEventosActionPerformed

    private void campoexpintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoexpintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoexpintActionPerformed

    private void ventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaActionPerformed
        if(ventana.getSelectedIndex()==0){
            containerCartas.removeAll();
            containerCartas.add(containerMod);
            containerCartas.repaint();
            containerCartas.revalidate();
        }else{
            containerCartas.removeAll();
            containerCartas.add(containerEventos);
            containerCartas.repaint();
            containerCartas.revalidate();
        }
    }//GEN-LAST:event_ventanaActionPerformed

    private void campoexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoexpActionPerformed

    private void campoexpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoexpMousePressed
        validarcampoModerador(campoexp,"Descripcion (No es obligatorio)", campoexpint, campometodo, camponombre, campotlf, campocorreo, campocedula);
    }//GEN-LAST:event_campoexpMousePressed

    private void campoevnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoevnombreMousePressed
        validarcampoModerador(campoevnombre,"Ingrese el nombre del evento", campolugar, campodescripcion, campocapMax);
    }//GEN-LAST:event_campoevnombreMousePressed

    private void campolugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campolugarMousePressed
        validarcampoModerador(campolugar,"Direccion", campoevnombre, campodescripcion, campocapMax);
    }//GEN-LAST:event_campolugarMousePressed

    private void campodescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campodescripcionMousePressed
        validarcampoModerador(campodescripcion,"Descripcion (No es obligatorio)", campolugar, campoevnombre, campocapMax);
    }//GEN-LAST:event_campodescripcionMousePressed

    private void campocapMaxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campocapMaxMousePressed
        validarcampoModerador(campocapMax,"Participantes que asistiran", campolugar, campodescripcion, campoevnombre);
    }//GEN-LAST:event_campocapMaxMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void campoevnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoevnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoevnombreActionPerformed

    private void campocapMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocapMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocapMaxActionPerformed

    private void botonComienzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComienzoActionPerformed
        horaComenzar.showPopup(this, WIDTH, WIDTH);
    }//GEN-LAST:event_botonComienzoActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        horaFinal.showPopup(this, WIDTH, WIDTH);
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void botonComienzoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComienzoMouseEntered
       herramientasVentanas.cambiarColor(botonComienzo, true);
    }//GEN-LAST:event_botonComienzoMouseEntered

    private void botonComienzoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComienzoMouseExited
       herramientasVentanas.cambiarColor(botonComienzo, false);
    }//GEN-LAST:event_botonComienzoMouseExited

    private void botonFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFinalizarMouseEntered
       herramientasVentanas.cambiarColor(botonFinalizar, true);
    }//GEN-LAST:event_botonFinalizarMouseEntered

    private void botonFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFinalizarMouseExited
       herramientasVentanas.cambiarColor(botonFinalizar, false);
    }//GEN-LAST:event_botonFinalizarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComienzo;
    private javax.swing.JButton botonFinalizar;
    private de.wannawork.jcalendar.JCalendarComboBox calendario;
    private javax.swing.JTextField campocapMax;
    private javax.swing.JTextField campocedula;
    private javax.swing.JTextField campocorreo;
    private javax.swing.JTextField campodescripcion;
    private javax.swing.JTextField campoevnombre;
    private javax.swing.JTextField campoexp;
    private javax.swing.JTextField campoexpint;
    private javax.swing.JTextField campolugar;
    private javax.swing.JTextField campometodo;
    private javax.swing.JTextField camponombre;
    private javax.swing.JTextField campotlf;
    private javax.swing.JPanel containerCartas;
    private javax.swing.JPanel containerEventos;
    private javax.swing.JPanel containerMod;
    private javax.swing.JPanel containerprincipal;
    private javax.swing.JLabel experiencias;
    private javax.swing.JLabel experienciascantidad;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel footereventos;
    private javax.swing.JPanel header;
    private com.raven.swing.TimePicker horaComenzar;
    private com.raven.swing.TimePicker horaFinal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limpiarEventos;
    private javax.swing.JButton limpiarMod;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel metodomoderar;
    private javax.swing.JLabel metodomoderar1;
    private javax.swing.JLabel metodomoderar2;
    private javax.swing.JLabel metodomoderar3;
    private javax.swing.JLabel metodomoderar4;
    private javax.swing.JLabel metodomoderar5;
    private javax.swing.JLabel metodomoderar6;
    private javax.swing.JLabel metodomoderar7;
    private javax.swing.JLabel metodomoderar8;
    private javax.swing.JPanel padre;
    private javax.swing.JButton registrarEventos;
    private javax.swing.JButton registrarMod;
    private javax.swing.JButton salirMod;
    private javax.swing.JButton salireventos;
    private javax.swing.JSeparator separadorcedula;
    private javax.swing.JSeparator separadorcorreo;
    private javax.swing.JSeparator separadornombre;
    private javax.swing.JSeparator separadortlf;
    private javax.swing.JPanel superior;
    private javax.swing.JPanel titulo;
    private javax.swing.JPanel titulo1;
    private javax.swing.JLabel titulomoderador;
    private javax.swing.JLabel titulomoderador1;
    private javax.swing.JComboBox<String> ventana;
    // End of variables declaration//GEN-END:variables
}
